### ISSUE TITLE
Exposing datadog metrics

### ISSUE THREAD

**Issue by hafizmujadid** [RustedBones/akka-http-metrics#17]
Hi, 
I don't see any example to expose datadog metrics. Is this functionality is supported or not? 

thanks

**Comment by RustedBones** [comment]
As stated in the [README](https://github.com/RustedBones/akka-http-metrics#datadog), exposing akka-http server metrics to datadog is supported via statsd:
```scala
import com.timgroup.statsd.StatsDClient
import fr.davit.akka.http.metrics.datadog.DatadogRegistry

val client: StatsDClient = ... // your statsd client

val registry = DatadogRegistry(client)
```

For instance:

```scala
  val registry = DatadogRegistry(new NonBlockingStatsDClient("test", "localhost", 8081))

  val route: Route = (get & path("message"))(complete(TestMessage("test", 1234)))

  Http().bindAndHandle(route.recordMetrics(registry, settings), "localhost", 8080)
```

You can check the messages sent to statsd by nunning necat like this: `netcat -ul 8081`

Is this what you are looking for ?

**Comment by hafizmujadid** [comment]
Yes, thanks for your quick response.
