### ISSUE TITLE
Request/response headers as metric dimensions

### ISSUE THREAD

**Issue by lucashimizu** [RustedBones/akka-http-metrics#227]
It would be nice to be able to configure some headers to be picked up as dimensions for a namespace, for example to track `user-agent` usage or responses from APIs marked with `deprecation`.

Is there any alternative suggestion for this, currently?

**Comment by RustedBones** [comment]
I've just published the `1.7.0-SNAPSHOT` artifacts. This should solve your issue. Can you give it a try and let me know ?
