### ISSUE TITLE
Add directive to provide custom dimensions

### ISSUE THREAD

**Issue by aleksandr-vin** [RustedBones/akka-http-metrics#246]
We provide graphql endpoint and need to populate operation name as dimension of metrics. Currently we use a workaround to add it as a suffix to `path` dimension:

```
def labeled(name: String): Directive0 = mapResponse { response =>
    response.addAttribute(HttpMetrics.PathLabel, s"($name)")
}

pathLabeled("graphql") {
      post {
        entity(as[GraphQLRequest]) { query =>
          labeled(query.operationName.getOrElse("unknown")) {
            ...
```

Would be nice to have it as a separate dimension. Plus we can populate `Referer` (after mapping into finite cardinality).

**Comment by RustedBones** [comment]
This is related to #227.
I faced some issues working on the next major. I'll probably try to backport some of the improvements to create a new release supporting custom dimensions

**Comment by RustedBones** [comment]
I just created a `1.7.0-SNAPSHPOT` release. Can you give it a try and let me know if it fits your needs?

**Comment by aleksandr-vin** [comment]
Thanks for implementation, @RustedBones!!

Here are my findings so far:

1. Error in the _README.md_: #254 
2. Swapped path and status labels in Prometheus: #255

**Comment by aleksandr-vin** [comment]
Also some thing that can make it more expressive. As the `withCustomDimensions` & `withServerDimensions` are supposed to be called with the static lists of dimensions, the code could be concise if varargs syntax is used.

**Comment by RustedBones** [comment]
Thank you so much @aleksandr-vin for testing the release and for the valuable feedback!
I've updated the snapshot. You can give another shot and if everything is OK I'll publish `v1.7.0`

**Comment by aleksandr-vin** [comment]
I've checked, it's awesome! Thanks for quick fix!

**Comment by aleksandr-vin** [comment]
You have only one typo in CHANGELOG.md: see `form` -> `from`:
```
- Change form sequence to varagrs API in settings
```
