### ISSUE TITLE
Custom dimensions

### ISSUE THREAD

**Issue by hafizmujadid** [RustedBones/akka-http-metrics#25]
Hi,

I was wondering how can we introduce more metrics such as counts per response code.  Can we extend the existing counters/timer/Gauge to introduce a new one according to needs? 

Thanks

**Comment by RustedBones** [comment]
I think what you are looking for is a possibility to add custom dimensions.

It is at the moment no possible, but we can think of giving the user more freedom on the labels for the response metrics. I think having the following

```scala
(HttpRequest, HttpResponse) => Seq[Dimension]
```

is enough for this case.

Would it help you @hafizmujadid ?

**Comment by hafizmujadid** [comment]
But what about if someone needs more matrices than what you already have provided?
