### ISSUE TITLE
Release 0.6.0 missing?

### ISSUE THREAD

**Issue by xperimental** [RustedBones/akka-http-metrics#26]
Hello,

It seems like the files for 0.6.0 are missing from Maven Central: https://search.maven.org/search?q=g:fr.davit%20AND%20a:akka-http-metrics-core_2.12&core=gav

Are they to be found somewhere else or did they not get uploaded?

**Comment by RustedBones** [comment]
Indeed.
I probably forget to promote the staging repository when releasing to sonatype.

Making the 0.6.0 release now

**Comment by RustedBones** [comment]
Release should be available for download now.
Thanks for reporting

**Comment by xperimental** [comment]
Yes, I can see it now. Thanks.
