### ISSUE TITLE
Implicit use of HttpMetricsRoute seems to no longer work

### ISSUE THREAD

**Issue by philvarner** [RustedBones/akka-http-metrics#33]
With the following code under Scala 2.12:

```
import fr.davit.akka.http.metrics.core.scaladsl.server.HttpMetricsRoute._
...
Http().bindAndHandle(route.recordMetrics(registry), "localhost", 8080)
```

even with scalac option `-language:implicitConversions`, I get the compile error:

```
... value recordMetrics is not a member of akka.http.scaladsl.server.Route
[error]     val server = Http().bindAndHandle(rootRoute.recordMetrics(metricsRegistry, settings), interface, port)
```

I'm using `"fr.davit" %% "akka-http-metrics-prometheus" % "0.6.0"`

However, this does work:

```
import fr.davit.akka.http.metrics.core.scaladsl.server.HttpMetricsRoute
...
val server = Http().bindAndHandle(HttpMetricsRoute(rootRoute).recordMetrics(metricsRegistry, settings), interface, port)
```

I feel it would be a good idea to update the example to use this explicit code that works under more situations.

**Comment by RustedBones** [comment]
I tried to reproduce but the code compiles without issue on my setup.
`recordMetrics` is found on `Route`.
Do you have a all required implicits in scope (`Materializer`, ...) ?

Can you maybe share you server setup to help for investigation ?

**Comment by RustedBones** [comment]
@philvarner Any news on this ?

**Comment by philvarner** [comment]
Sorry for not getting back with you.  I created a minimal reproduction here: https://github.com/philvarner/metrics-bug  
with the same issu:

```
[info] Compiling 1 Scala source to /Users/pvarner/code/metrics-bug/target/scala-2.12/classes ...
[error] /Users/pvarner/code/metrics-bug/src/main/scala/foo/StandardHttpService.scala:38:11: value recordMetrics is not a member of akka.http.scaladsl.server.Route
[error]     route.recordMetrics(metricsRegistry, metricsSettings)
[error]           ^
```

**Comment by RustedBones** [comment]
It's confusing...

![image](https://user-images.githubusercontent.com/2845540/74861911-6a579a00-534b-11ea-82f8-4973d06ece20.png)

I tried to clear the ivy/coursier cache to make sure I don't run in a locally published version of the library

**Comment by philvarner** [comment]
Sorry, I accidentally discovered how to make it work before committing that code. I've pushed the changes to make it break. It seems to only be an issue when it's in the companion object's `apply` method -- when I rename that method to `f1` like in original code, it works. Why that would be is beyond my Scala knowledge.

**Comment by philvarner** [comment]
I'm not even sure why this is code is designed as an object in the first place. Maybe just documenting that this doesn't work as a naive user might expect in an object is a good resolution.

**Comment by RustedBones** [comment]
> Maybe just documenting that this doesn't work

It compiled without problem on a clean clone with clean cache
