### ISSUE TITLE
Support for Apache Pekko

### ISSUE THREAD

**Issue by cjodeaw** [RustedBones/akka-http-metrics#336]
With Lightbend's [licensing change](https://www.infoq.com/news/2022/09/akka-no-longer-open-source/) for Akka, many projects will migrate to [Apache Pekko](https://cwiki.apache.org/confluence/display/INCUBATOR/PekkoProposal). 

Are there any plans for a `pekko-http-metrics`?

**Comment by RustedBones** [comment]
hi @cjodeaw. Following Lightbend's licencing change, I've [pinned](https://github.com/RustedBones/akka-http-metrics/blob/main/.scala-steward.conf) the akka open source versions.

I think you are right, it's about time to bring metrics support to `pekko-http`. I'll create a fork soon for that.

**Comment by cjodeaw** [comment]
HI Michel, 

I opened a pull request with an initial stab at supporting pekko.  May be of some use to you. 

thanks
Conrad

**Comment by RustedBones** [comment]
Fork is available [here](https://github.com/RustedBones/pekko-http-metrics). Do you need a snapshot ?

**Comment by RustedBones** [comment]
`pekko-http-metrics` v1.0.0 is [available](https://github.com/RustedBones/pekko-http-metrics/releases/tag/v1.0.0) now!
