### ISSUE TITLE
Custom counter names

### ISSUE THREAD

**Issue by bjolletz** [RustedBones/akka-http-metrics#34]
Hi!

Is it possible to somehow customize the name of the counters? I've looked at the code but it doesn't look like it.

If I want to use this lib in several different microservices (or similar), then I would want to know which microservice the counters belong to. So being able to specify a counter name prefix in the settings would be useful.

Thanks and regards,
Daniel

**Comment by RustedBones** [comment]
Thanks a lot for reporting @bjolletz .

I'll try to release the 1.0.0 ASAP
