### ISSUE TITLE
Prometheus duration conversion is off by x10

### ISSUE THREAD

**Issue by amerpersonal** [RustedBones/akka-http-metrics#4]
Hi,

I setup akka-http-metrics to my akka http project and I have following metrics for requests duration:

akka_http_requests_duration_seconds{quantile="0.75",} 30.29
akka_http_requests_duration_seconds{quantile="0.95",} 30.29
akka_http_requests_duration_seconds{quantile="0.98",} 30.29
akka_http_requests_duration_seconds{quantile="0.99",} 30.29
akka_http_requests_duration_seconds{quantile="0.999",} 30.29
akka_http_requests_duration_seconds_count 6.0
akka_http_requests_duration_seconds_sum 139.39999999999998

This is local testing so it takes forever :).
But response time is never more than 3 seconds, but it show 30 seconds here. Does it somehow mean 3 seconds? 

For other request I see similar things, when request lasts 6 ms, it shows 0.06 seconds (should be 0.006)

**Comment by RustedBones** [comment]
Good catch. There is actually a bug in the Prometheus conversion.
Thanks for reporting!

**Comment by RustedBones** [comment]
Fixed in release `v0.2.1`
