### ISSUE TITLE
Not all metrics are exposed for Prometheus

### ISSUE THREAD

**Issue by zzvara** [RustedBones/akka-http-metrics#55]
Project using:

AKKA 2.6.6
AKKA HTTP 10.1.12

```
    "fr.davit" %% "akka-http-metrics-prometheus" % "1.1.1"
```

Creating registry as:

```
  protected val prometheusCollector = CollectorRegistry
    .defaultRegistry
  protected val prometheusSettings = PrometheusSettings
    .default
    .withNamespace(metricsNamespace)
    .withIncludeMethodDimension(true)
    .withIncludePathDimension(true)
    .withIncludeStatusDimension(true)
    .withDefineError(_.status.isFailure)
  protected val prometheusRegistry =
    PrometheusRegistry(prometheusCollector, prometheusSettings)
```

Exposing as:

```
      pathLabeled("metrics") {
        import fr.davit.akka.http.metrics.prometheus.marshalling.PrometheusMarshallers._
        metrics(prometheusRegistry)
      } ~
```

But only the following metrics are exposed, moreover, it should show at least 1 for connection_total:

```
# HELP server_connections_active Active TCP connections
# TYPE server_connections_active gauge
server_connections_active 0.0
# HELP server_connections_total Total TCP connections
# TYPE server_connections_total counter
server_connections_total 0.0
```

**Comment by RustedBones** [comment]
Hi @zzvara, thanks for reporting your issue.
Are you using the very same registry in the `recordMetrics` ?

```scala
Http().bindAndHandle(route.recordMetrics(prometheusRegistry), "localhost", 8080)
```

**Comment by zzvara** [comment]
@RustedBones I missed that, but how should I provide all the implicit for this:

```
  def recordMetrics(metricsHandler: HttpMetricsHandler)(
      implicit
      routingSettings: RoutingSettings,
      parserSettings: ParserSettings,
      materializer: Materializer,
      routingLog: RoutingLog,
      executionContext: ExecutionContextExecutor = null,
      rejectionHandler: RejectionHandler = RejectionHandler.default,
      exceptionHandler: ExceptionHandler = null
  ): Flow[HttpRequest, HttpResponse, NotUsed] = {
```

I think example codes would not work due to this detail missing.

**Comment by RustedBones** [comment]
The implicits are exactly the same as `akka-http`. You need the `ActorSystem` and the `Materializer`, the others are derived or optionals

**Comment by zzvara** [comment]
Thanks, I have made it to work.

Remark:
It interferes with `ScalatestRouteTest`, since `ScalatestRouteTest` expects a `Route`, not `Flow[...]`. I found no clear way to convert `Flow[...]` back to `Route`, therefore I had to keep a `Route` intact while converting it to `Flow[...]` using `recordMetrics` and *then* pass it to `bindAndHandle`. This got me confused, but it works well now.

Thanks!

**Comment by RustedBones** [comment]
Yes, this is a good point. You'cant easily test your route with the metrics since it triggers the conversion from Route -> Flow.
I'll have a look if this is possible to give some helpers for testing
