### ISSUE TITLE
More detail on how to plot relevant Duration Config on Prometheus

### ISSUE THREAD

**Issue by gunjdesai** [RustedBones/akka-http-metrics#56]
This is more of a question, than an issue.

I am currently using the prometheus package, and am publishing duration config exactly similar to the example that you've provided.
```
val settings = PrometheusSettings
      .default
      .withDurationConfig(Buckets(1, 2, 3, 5, 8, 13, 21, 34))
      .withReceivedBytesConfig(Quantiles(0.5, 0.75, 0.9, 0.95, 0.99))
      .withSentBytesConfig(PrometheusSettings.DefaultQuantiles)
```

On prometheus, i am setting up the following graph, which has the same query for 99, 95, 90 and 50 percentile.
`histogram_quantile(0.99, avg(rate(akka_http_responses_duration_seconds_bucket[5m])) by (le))`

<img width="660" alt="Screenshot 2020-07-27 at 1 27 39 PM" src="https://user-images.githubusercontent.com/7438622/88517865-2741d700-d00d-11ea-967b-bb693cd6fb02.png">

The response times displayed in the graph are known to be inaccurate because i have set an overall timeout at **_200ms._**
Sorry for my lack of knowledge here, but if there would a little more explanation around how to configure the duration config would really help me debug better and resolve the issue on my end.

**Comment by RustedBones** [comment]
I think the issue comes from the [histogram_quantile function]( https://prometheus.io/docs/prometheus/latest/querying/functions/#histogram_quantile). Seems in the doc it requires `sum` instead of average.

Can you `curl` the endpoint and paste the result you have for the `akka_http_responses_duration_seconds_bucket` metrics ? This will help for investigation.

**Comment by gunjdesai** [comment]
I did try using sum for the histogram_quantile function but it yields the same result.

The result of the metrics endpoint is as follows
```
# HELP akka_http_connections_active Active TCP connections
# TYPE akka_http_connections_active gauge
akka_http_connections_active 5.0
# HELP akka_http_requests_active Active HTTP requests
# TYPE akka_http_requests_active gauge
akka_http_requests_active 0.0
# HELP akka_http_responses_size_bytes HTTP response size
# TYPE akka_http_responses_size_bytes summary
akka_http_responses_size_bytes{quantile="0.75",} NaN
akka_http_responses_size_bytes{quantile="0.95",} NaN
akka_http_responses_size_bytes{quantile="0.98",} NaN
akka_http_responses_size_bytes{quantile="0.99",} NaN
akka_http_responses_size_bytes{quantile="0.999",} NaN
akka_http_responses_size_bytes_count 1.0
akka_http_responses_size_bytes_sum 81.0
# HELP akka_http_connections_total Total TCP connections
# TYPE akka_http_connections_total counter
akka_http_connections_total 218092.0
# HELP akka_http_responses_duration_seconds HTTP response duration
# TYPE akka_http_responses_duration_seconds histogram
akka_http_responses_duration_seconds_bucket{le="1.0",} 234400.0
akka_http_responses_duration_seconds_bucket{le="2.0",} 234400.0
akka_http_responses_duration_seconds_bucket{le="3.0",} 234400.0
akka_http_responses_duration_seconds_bucket{le="5.0",} 234400.0
akka_http_responses_duration_seconds_bucket{le="8.0",} 234400.0
akka_http_responses_duration_seconds_bucket{le="13.0",} 234400.0
akka_http_responses_duration_seconds_bucket{le="21.0",} 234400.0
akka_http_responses_duration_seconds_bucket{le="34.0",} 234400.0
akka_http_responses_duration_seconds_bucket{le="+Inf",} 234400.0
akka_http_responses_duration_seconds_count 234400.0
akka_http_responses_duration_seconds_sum 1.632999999999979
# HELP akka_http_responses_total HTTP responses
# TYPE akka_http_responses_total counter
akka_http_responses_total 234400.0
# HELP akka_http_requests_total Total HTTP requests
# TYPE akka_http_requests_total counter
akka_http_requests_total 234400.0
# HELP akka_http_requests_size_bytes HTTP request size
# TYPE akka_http_requests_size_bytes summary
akka_http_requests_size_bytes{quantile="0.5",} 0.0
akka_http_requests_size_bytes{quantile="0.75",} 0.0
akka_http_requests_size_bytes{quantile="0.9",} 0.0
akka_http_requests_size_bytes{quantile="0.95",} 0.0
akka_http_requests_size_bytes{quantile="0.99",} 0.0
akka_http_requests_size_bytes_count 234400.0
akka_http_requests_size_bytes_sum 425.0
```

**Comment by RustedBones** [comment]
Your buckets are actually miss-configured for your usage:
```scala
Buckets(1, 2, 3, 5, 8, 13, 21, 34)
```
tells your smallest bucket is `[0s, 1s[` which contains all of your requests.
You'll then not ba able to precisely plot the quantiles.

If your timeout is 200ms, I would suggest to define your bucket more like

```scala
Buckets(
  0.01, 0.02, 0.03, 0.04, 0.05 0.06, 0.07, 0.08, 0.09, 0.1,
  0.11, 0.12, 0.13, 0.14, 0.15 0.16, 0.17, 0.18, 0.19, 0.2,
  0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1
)
```

**Comment by gunjdesai** [comment]
Oh ok, my bad. Let me try this out.

**Comment by RustedBones** [comment]
No worries. The example given in the README is not really meant to be used as is.
Settings is already configured with more sensible defaults [here](https://github.com/RustedBones/akka-http-metrics/blob/2623e626ebe424d0f3a30c17dd9d3cb3ce1e5099/prometheus/src/main/scala/fr/davit/akka/http/metrics/prometheus/PrometheusSettings.scala#L105) for more sensible defaults.

Just overwrite what you need.

**Comment by gunjdesai** [comment]
Worked like a dream. Thank you so much for your instant help. Really appreciate it.
