### ISSUE TITLE
Push v1.3.0 for Scala 2.12 to oss.sonatype.org

### ISSUE THREAD

**Issue by pdezwart** [RustedBones/akka-http-metrics#71]
It looks like you may have only pushed v1.3.0 for Scala 2.13. Any chance you can publish the 2.12 version as well please?

Thanks!

**Comment by RustedBones** [comment]
Oops, i forgot to cross publish.
Will do and try to automate this so it won't happen again.
Thanks for reporting!

**Comment by RustedBones** [comment]
Published!
