### ISSUE TITLE
StatusGroup / Path for requests?

### ISSUE THREAD

**Issue by jundong321** [RustedBones/akka-http-metrics#74]
Since rejected response can't have labeled path, there is no way to know exactly what request is rejected. Can we add StatusGroup and Path to requests?

**Comment by RustedBones** [comment]
Hi @jundong321.
Indeed, this is a councious design decision that unhandled path have a fixed label

> You must also be careful about cardinality: see [here](https://prometheus.io/docs/practices/naming/#labels)

An attacker can hammer your service with random paths requests that will blow up your registry and also increase costs if you export the metrics to an centralized logging service like datadog or AWS CloudWatch.

There is no easy way to change this behavior. I would advise use a [custom rejection handler](https://doc.akka.io/docs/akka-http/current/routing-dsl/rejections.html#customizing-rejection-handling) with a specific `handleNotFound` that will log the rejected path, or other type of rejection you want to log.

Concerning the status group, it should be available on the rejected responses.

Hope this helps

**Comment by jundong321** [comment]
thanks the the reply!
