### ISSUE TITLE
metric for "active_connections" ?

### ISSUE THREAD

**Issue by bilal-fazlani** [RustedBones/akka-http-metrics#9]
First of all, thank you so much! This is tool so convenient.

Coming to my question. I see that there is a metric for active requests, but I was wondering if it's possible to get a metric for active connections as well?

I have been [trying to get hold of active connections](https://stackoverflow.com/questions/56879865/how-to-get-current-number-of-connections-of-an-akka-http-application) from an akka-http application, but as of now, I have no idea where to get it from.

**Comment by RustedBones** [comment]
Hi @bilal-fazlani , 
I'm trying to keep this library as a plug-in to akka-http.
Unfortunately, I didn't find a easy way to access the underlying connection pool used by the server.

I'll try to check again if there is a possibility to do this through the extension module. I would also like to get real network metrics for the requests like curl provides (time to server, DNS resolution, ...)

**Comment by RustedBones** [comment]
@bilal-fazlani I found a way to compute the connection metrics for the `akka-http` server.
Can you review the PR to be sure I didn't miss something you need.

I'll make a new release as soon as it is merged

**Comment by bilal-fazlani** [comment]
It seems perfect. Thank you much!

**Comment by RustedBones** [comment]
Thank you for posting the feature request :)

**Comment by bilal-fazlani** [comment]
Hi,
``` scala
    {
      implicit val executionContext: ExecutionContextExecutor = effectiveEC
      Flow[HttpRequest]
        .mapAsync(1)(metricsHandler(registry, settings, Route.asyncHandler(route)))
        .watchTermination() { case (mat, completion) =>
          // every connection materializes a stream
          registry.connections.inc()
          registry.connected.inc()
          completion.onComplete(_ => registry.connected.dec())
          mat
        }
    }
```


here `Flow[HttpRequest]` makes me wonder whether we are capturing count of requests or connections ?

**Comment by RustedBones** [comment]
These are the connections:
- Every connections materializes a `Flow`
- Several `HttpRequest` can be processed through this `Flow` 

So if we count how many times we materialize the flow, we have the number of connections.

I have created this test:
```scala
it should "compute the number of connections" in  {
    implicit val registry = new TestRegistry
    val server = mockFunction[RequestContext, Future[RouteResult]]

    val stream = Source((0 until 5).map(_ => HttpRequest())).via(server.recordMetrics(registry)).toMat(Sink.ignore)(Keep.right)
    val completions = (0 until 3).map(_ => stream.run())
    Future.sequence(completions).futureValue
    registry.connections.value shouldBe 3
  }
```
We materialize the stream 3 times, every stream processes 5 requests.
The connection count is 3. The request count would be 15 in this case.

**Comment by bilal-fazlani** [comment]
Cool! Thanks!
